version: "3" # 파일 규격 버전

services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  # 로드밸런싱
  #
  # nginx 컨테이너
  nginx:
    image: nginx:1.21.0
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80" # 80(aws):80(컨테이너) # localhost:80 컨테이너의 80
    depends_on:
      - docker-demo1

  docker-demo1:
    image: foodeats # dockerdemo라는 이미지를 사용하고 해당 이미지를 컨테이너로 만들어주는
    # docker-demo1 해당 컨테이너의 8080 포트가 열려있고
    container_name:
      server1
    ports:
      - "8080:8080" #localhost:8080
