version: "3" # 파일 규격 버전

services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  # 로드밸런싱
  #
  nginx:
    image: nginx:1.21.0
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80 # 80(로컬):80(컨테이너) # localhost:80 컨테이너의 80
